title: Alejandro Machado
email: alejandro@macha.do
description: Alejandro Machado
url: "https://ale.macha.do"
twitter: alegw

baseurl: ""
permalink: /:title/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
collections:
  my_posts:
    output: true