title: Alejandro Machado
email: alejandro@macha.do
description: Alejandro Machado
url: "https://ale.macha.do"
twitter: alegw

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed