title: Alejandro Machado
email: alejandro@macha.do
description: Essays on education, technology, money, and building products in Latin America.
url: "https://ale.macha.do"
twitter: alegw

baseurl: ""
permalink: /:title/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-sitemap
collections:
  my_posts:
    output: true
