title: Ale Machado's writing
email: alejandro@macha.do
description: Ale Machado's writing
url: "https://ale.macha.do"
twitter: alegw

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed